# 70.03 Создание одномерных массивов в NumPy

In [2]:
import numpy as np
np

<module 'numpy' from 'C:\\Users\\shura\\anaconda3\\Lib\\site-packages\\numpy\\__init__.py'>

In [3]:
# создание массива из списка
nums_array = np.array([1, 2, 3, 4])
nums_array

array([1, 2, 3, 4])

In [4]:
# создание массива из кортежа
nums_array = np.array((1, 2, 3, 4))
nums_array

array([1, 2, 3, 4])

In [5]:
#naarray - n-dimensional array
type(nums_array)

numpy.ndarray

In [6]:
# получение доступа к элементу массива - элементы упорядочены
nums_array[0]

1

In [7]:
nums_array[-1]

4

# 70.04 Форма, размерность и тип данных в NumPy

In [8]:
nums_array = np.array([1, 2, 3, 4])

# смотрим список доступных атрибутов
nums_array.shape

(4,)

In [9]:
# форма массива
nums_array.shape

(4,)

In [10]:
# размерность массива
nums_array.ndim

1

In [11]:
# количество элементов в массиве
nums_array.size

4

In [12]:
# тип значений в массиве
nums_array.dtype

dtype('int32')

In [13]:
# размер каждого элемента 
# (сколько занимает места в памяти: колво байт)
nums_array.itemsize

4

In [14]:
# создадим массив с элементами разных типов
# получаем массив строк: приведение всех значений к одному типу
np.array([True, 10, 'abs', 5.5])

array(['True', '10', 'abs', '5.5'], dtype='<U32')

In [15]:
np.array([True, 10, 'abs', 5.5]).dtype

dtype('<U32')

In [16]:
np.array([True, 10, 'abs', 5.5]).dtype.name

'str1024'

In [17]:
np.array([True, 10, 'abs', 5.5]).itemsize

128

In [18]:
# сохрание объектов в качестве переменных
obj_array = np.array([{'city': 'London'},
                      {'city': 'Boston'}])
obj_array                  

array([{'city': 'London'}, {'city': 'Boston'}], dtype=object)

In [19]:
obj_array .dtype.name

'object'

In [20]:
# т.е. сохраняются ссылки на адреса в памяти
obj_array .itemsize

8

# 70.05 Двухмерные массивы в NumPy

In [21]:
first = np.array([[1,2,3],[4,5,6]])
first

array([[1, 2, 3],
       [4, 5, 6]])

In [22]:
# попробуем добавить разное колво элементов
# получим ошибку
first = np.array([[1,2,3],[4,5,6,7]])
first

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

In [23]:
# получаем 2 ряда и 3 колонки
first = np.array([[1,2,3],[4,5,6]])
print(first)

# получаем 2 ряда и 3 колонки
print("\nshape:", first.shape)
print("ndim:", first.ndim)
print("size:", first.size)

[[1 2 3]
 [4 5 6]]

shape: (2, 3)
ndim: 2
size: 6


In [24]:
second = np.array([[7,8,9], [10,11,12]])
print(second)
print("\nshape:", second .shape)
print("ndim:", second.ndim)
print("size:", second.size)

[[ 7  8  9]
 [10 11 12]]

shape: (2, 3)
ndim: 2
size: 6


In [25]:
# сложение двух массивов
# поэлементное сложение
first + second

array([[ 8, 10, 12],
       [14, 16, 18]])

In [26]:
# арифметические операции - поэлементно
print("Исходный массив")
print(first)

print(30*'-')
print("Прибавление числа к массиву")
print(first + 100)

print(30*'-')
print("Вычитание числа")
print(first - 100)

print(30*'-')
print("Умножение на число")
print(first * 50)

print(30*'-')
print("Деление на число")
print(first / 100)

print(30*'-')
print("Исходный массив не меняется")
print(first)

Исходный массив
[[1 2 3]
 [4 5 6]]
------------------------------
Прибавление числа к массиву
[[101 102 103]
 [104 105 106]]
------------------------------
Вычитание числа
[[-99 -98 -97]
 [-96 -95 -94]]
------------------------------
Умножение на число
[[ 50 100 150]
 [200 250 300]]
------------------------------
Деление на число
[[0.01 0.02 0.03]
 [0.04 0.05 0.06]]
------------------------------
Исходный массив не меняется
[[1 2 3]
 [4 5 6]]


# 70.07 Слияние массивов NumPy

In [27]:
first = np.array([[1,2,3],[4,5,6]])
# чтобы вытащить элемент - указываем координаты
print('first[1,1]: ',first[1,1])
print('first[1][1]: ',first[1][1])

first[1,1]:  5
first[1][1]:  5


In [28]:
# слияние двух массивов
first = np.array([[1,2,3],[4,5,6]])
second = np.array([[7,8,9], [10,11,12]])

print('axis=0\n', np.concatenate((first, second), axis=0))
print('\naxis=1\n', np.concatenate((first, second), axis=1))

axis=0
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

axis=1
 [[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


In [29]:
# порядок следования в concatenate играет роль
print('axis=0\n', np.concatenate((second, first), axis=0))
print('\naxis=1\n', np.concatenate((second, first), axis=1))

axis=0
 [[ 7  8  9]
 [10 11 12]
 [ 1  2  3]
 [ 4  5  6]]

axis=1
 [[ 7  8  9  1  2  3]
 [10 11 12  4  5  6]]


# 70.08 Соединение одномерных массивов

In [30]:
# у одномерных массивов только одна ось - ось 0
np.concatenate((np.array([1,2,3,4]), np.array([5,6,7,8])))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [31]:
# по оси 1 - не получится!
# ибо у них нет оси 1
np.concatenate((np.array([1,2,3,4]), np.array([5,6,7,8])), axis=1)

AxisError: axis 1 is out of bounds for array of dimension 1

# 70.09 Заполнение массива нулями и единицами

## Заполняем нулями

In [32]:
# строки - столбцы
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [33]:
# строки - столбцы - ряд
np.zeros((3,4,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [34]:
# заполним интами
np.zeros((3,4), dtype=int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [35]:
# заполним boolean
np.zeros((3,4), dtype=bool)

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [36]:
# заполним строками
np.zeros((3,4), dtype=str)

array([['', '', '', ''],
       ['', '', '', ''],
       ['', '', '', '']], dtype='<U1')

## Заполняем единицами

In [37]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [38]:
np.ones((3,4), dtype=int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [39]:
np.ones((3,4), dtype=str)

array([['1', '1', '1', '1'],
       ['1', '1', '1', '1'],
       ['1', '1', '1', '1']], dtype='<U1')

In [40]:
np.ones((3,4), dtype=bool)

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

# 70.10 Модуль random для массивов NumPy

In [41]:
np.random.random(5)

array([0.03870136, 0.34211944, 0.17080842, 0.99372455, 0.23822534])

In [42]:
np.random.random((2,4))

array([[0.64796163, 0.44278112, 0.46868659, 0.86552482],
       [0.78929056, 0.3673727 , 0.13717647, 0.98907251]])

# 70.11 Псевдо случайные числа

In [43]:
np.random.seed(0)
np.random.random((2,4))

array([[0.5488135 , 0.71518937, 0.60276338, 0.54488318],
       [0.4236548 , 0.64589411, 0.43758721, 0.891773  ]])

In [44]:
np.random.seed(10)
np.random.random((2,4))

array([[0.77132064, 0.02075195, 0.63364823, 0.74880388],
       [0.49850701, 0.22479665, 0.19806286, 0.76053071]])

In [45]:
np.random.seed(0)
np.random.random((2,4))

array([[0.5488135 , 0.71518937, 0.60276338, 0.54488318],
       [0.4236548 , 0.64589411, 0.43758721, 0.891773  ]])

# 70.12 Методы randint, uniform и choice

In [48]:
np.random.randint(10, 20, size=(2,4))

array([[18, 19, 14, 13],
       [10, 13, 15, 10]])

In [49]:
np.random.seed(15)
np.random.randint(10, 20, size=(2,4))

array([[18, 15, 15, 17],
       [10, 17, 15, 16]])

In [54]:
np.random.seed(10)
np.random.random(size=(3,5))

array([[0.77132064, 0.02075195, 0.63364823, 0.74880388, 0.49850701],
       [0.22479665, 0.19806286, 0.76053071, 0.16911084, 0.08833981],
       [0.68535982, 0.95339335, 0.00394827, 0.51219226, 0.81262096]])

In [53]:
# same as random
np.random.seed(10)
np.random.uniform(size=(3,5))

array([[0.77132064, 0.02075195, 0.63364823, 0.74880388, 0.49850701],
       [0.22479665, 0.19806286, 0.76053071, 0.16911084, 0.08833981],
       [0.68535982, 0.95339335, 0.00394827, 0.51219226, 0.81262096]])

In [56]:
# я могу указать диапазон
# uniform - любое значение внутри диапазона - равновероятно 
np.random.seed(10)
np.random.uniform(10, 50, size=(3,5))

array([[40.85282573, 10.83007797, 35.3459294 , 39.9521553 , 29.94028049],
       [18.99186582, 17.92251459, 40.42122849, 16.76443346, 13.53359257],
       [37.41439273, 48.13573385, 10.15793065, 30.48769054, 42.50483847]])

In [57]:
# выбор элементов из массива
np.random.seed(10)
np.random.choice(np.array([1,2,3]), size=20)

array([2, 2, 1, 1, 2, 1, 2, 2, 1, 2, 2, 3, 1, 2, 1, 3, 1, 3, 1, 1])

In [58]:
np.random.seed(10)
np.random.choice(np.array([1,2,3]), size=(3,4))

array([[2, 2, 1, 1],
       [2, 1, 2, 2],
       [1, 2, 2, 3]])

# 70.13 Методы arange и reshape

In [68]:
print('np.arange(10):', np.arange(10))
print('np.arange(10.5):', np.arange(10.5))
print('np.arange(15,25):', np.arange(15,25))
print('np.arange(20,30,3):', np.arange(20,30,3))
print('np.arange(-20,30,5):', np.arange(-20,30,5))
print('np.arange(-20,30,5):', np.arange(start=-20,stop=30,step=5))

np.arange(10): [0 1 2 3 4 5 6 7 8 9]
np.arange(10.5): [ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
np.arange(15,25): [15 16 17 18 19 20 21 22 23 24]
np.arange(20,30,3): [20 23 26 29]
np.arange(-20,30,5): [-20 -15 -10  -5   0   5  10  15  20  25]
np.arange(-20,30,5): [-20 -15 -10  -5   0   5  10  15  20  25]


In [81]:
print('Исходный: ', np.arange(20))
print('\nreshape([2,10]:\n ', np.arange(20).reshape([2,10]))
print('\nreshape([2,2,5]:\n ', np.arange(20).reshape([2,2,5]))
print('\nreshape([4,5]:\n ', np.arange(20).reshape([4,5]))

Исходный:  [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]

reshape([2,10]:
  [[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]]

reshape([2,2,5]:
  [[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]]

reshape([4,5]:
  [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [84]:
np.random.random((10,)).reshape([5,2])

array([[0.51313824, 0.65039718],
       [0.60103895, 0.8052232 ],
       [0.52164715, 0.90864888],
       [0.31923609, 0.09045935],
       [0.30070006, 0.11398436]])

In [86]:
# можно использовать кортеж
np.random.random((10,)).reshape((5,2))

array([[0.88393648, 0.32551164],
       [0.1650159 , 0.39252924],
       [0.09346037, 0.82110566],
       [0.15115202, 0.38411445],
       [0.94426071, 0.98762547]])

# 70.14 Метод flatten для трансформации в одномерный массив

In [87]:
np.random.seed(10)
np.random.randint(50,80,(4,3,3))

array([[[59, 79, 54],
        [65, 50, 67],
        [77, 78, 75]],

       [[79, 66, 79],
        [67, 76, 58],
        [59, 50, 60]],

       [[58, 72, 54],
        [69, 66, 54],
        [65, 61, 72]],

       [[74, 61, 76],
        [51, 58, 54],
        [64, 67, 69]]])

In [89]:
# получаю одномерный массив из многомерного
np.random.seed(10)
np.random.randint(50,80,(4,3,3)).flatten()

array([59, 79, 54, 65, 50, 67, 77, 78, 75, 79, 66, 79, 67, 76, 58, 59, 50,
       60, 58, 72, 54, 69, 66, 54, 65, 61, 72, 74, 61, 76, 51, 58, 54, 64,
       67, 69])

In [95]:
print(np.arange(12).reshape((3,4)))
print(np.arange(12).reshape((3,4)).flatten())

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[ 0  1  2  3  4  5  6  7  8  9 10 11]


# 70.15 Одномерные массивы в NumPy - Примеры 1, 2

## 1. Calculating total revenue

In [107]:
prices = np.array([19.99, 29.99, 14.99, 9.99, 24.99])
prices

array([19.99, 29.99, 14.99,  9.99, 24.99])

In [108]:
quantities = np.array([10,5,8,12,3])
quantities

array([10,  5,  8, 12,  3])

In [109]:
revenue_per_product = prices * quantities
revenue_per_product

array([199.9 , 149.95, 119.92, 119.88,  74.97])

In [110]:
total_revenue = np.sum(revenue_per_product)
total_revenue

664.62

## 2. Analyzing Blog Post Stats

In [100]:
views = np.array([1000, 500, 800, 1200, 300, 600])
views

array([1000,  500,  800, 1200,  300,  600])

In [102]:
max_views = np.max(views)
max_views

1200

In [103]:
min_views = np.min(views)
min_views

300

In [104]:
avg_views = np.mean(views)
avg_views

733.3333333333334

In [105]:
avg_views = np.round(np.mean(views),2)
avg_views

733.33

In [106]:
total_views = np.sum(views)
total_views

4400

# 70.16 Одномерные массивы в NumPy - Примеры 3, 4

## 3. Splitting Order into Batches

In [129]:
order_ids = np.array([1001, 1002, 1003, 1004, 1005, 1006, 1007, 1008, 1009])
order_ids

array([1001, 1002, 1003, 1004, 1005, 1006, 1007, 1008, 1009])

In [130]:
batches = np.split(order_ids, 3)
batches

[array([1001, 1002, 1003]),
 array([1004, 1005, 1006]),
 array([1007, 1008, 1009])]

In [131]:
for batch in batches:
    print(batch)

[1001 1002 1003]
[1004 1005 1006]
[1007 1008 1009]


In [132]:
for batch in batches:
    print('Firt element in the batch:', batch[0])
    print('Second element in the batch:', batch[1])

Firt element in the batch: 1001
Second element in the batch: 1002
Firt element in the batch: 1004
Second element in the batch: 1005
Firt element in the batch: 1007
Second element in the batch: 1008


In [133]:
for i, batch in enumerate(batches):
    print(f'Batch number: {i}')
    print('Firt element in the batch:', batch[0])
    print( 'Second element in the batch:', batch[1])
    print('')

Batch number: 0
Firt element in the batch: 1001
Second element in the batch: 1002

Batch number: 1
Firt element in the batch: 1004
Second element in the batch: 1005

Batch number: 2
Firt element in the batch: 1007
Second element in the batch: 1008



## 4. Categorizing Product Ratings

In [134]:
ratings = np.array([4.5, 3.2, 2.8, 5.0, 4.1, 3.9, 2.5, 4.7])
ratings

array([4.5, 3.2, 2.8, 5. , 4.1, 3.9, 2.5, 4.7])

In [135]:
# разбиваем массив на два массива:
# в одном плохие рейтинги, в другом - хорошие
positive_ratings = ratings[ratings >= 4.0]
positive_ratings

array([4.5, 5. , 4.1, 4.7])

In [136]:
negative_ratings = ratings[ratings < 4.0]
negative_ratings

array([3.2, 2.8, 3.9, 2.5])

# 70.17 Двухмерные массивы в NumPy - Пример 5

## 5.Calculate Total and Average quantities sold

In [140]:
# Each column is specific product: 4 товара
# Each row is specific order: 2 заказа
order_quantities = np.array([[5,3,2,7], [10,6,3,9]])
order_quantities

array([[ 5,  3,  2,  7],
       [10,  6,  3,  9]])

In [141]:
# без указания оси - получим сумму всех элементов
total_quantities_sold = np.sum(order_quantities)
total_quantities_sold

45

In [142]:
# нужно указать - по какой оси будем суммировать
# мы хотим суммировать по оси 0
# получим сумму по колонкам
total_quantities_sold = np.sum(order_quantities, axis=0)
total_quantities_sold

array([15,  9,  5, 16])

In [145]:
# нужно указать - по какой оси будем суммировать
# мы хотим суммировать по оси 1
# получим сумму по строкам
total_products_per_order = np.sum(order_quantities, axis=1)
total_products_per_order

array([17, 28])

In [148]:
# среднее колво товаров проданных по всем заказам
average_quantities_sold = np.mean(order_quantities, axis=0)
average_quantities_sold

array([7.5, 4.5, 2.5, 8. ])

# 70.18 Двухмерные массивы в NumPy - Пример 6

## 6. Calculate Average product Rating and Maximum rating per Category

In [149]:
# каждый ряд - отдельный товар
# у каждого товара - по 4 оценки
product_rating = np.array([
    [4.5, 3.2, 2.5, 5.0],
    [4.3, 3.8, 1.0, 4.8],
    [2.0, 3.6, 4.7, 0.5],
])
product_rating

array([[4.5, 3.2, 2.5, 5. ],
       [4.3, 3.8, 1. , 4.8],
       [2. , 3.6, 4.7, 0.5]])

In [159]:
# Cредний рейтинг по каждому товару
average_rating_per_category = np.mean(product_rating, axis=0)
average_rating_per_category

array([3.6       , 3.53333333, 2.73333333, 3.43333333])

In [161]:
# Средний рейтинг по каждой категории
average_rating_per_product = np.mean(product_rating, axis=1)
average_rating_per_product

array([3.8  , 3.475, 2.7  ])

In [162]:
# Макс рейтинг в каждой категории
max_rating_per_category = np.max(product_rating, axis=0)
max_rating_per_category

array([4.5, 3.8, 4.7, 5. ])

# 70.19 Трехмерные массивы в NumPy - Пример 7

## 7. Generation of the sample stock data

In [170]:
companies = ['Google', 'Microsoft', 'Apple']
days = ['Mon 1 April', 'Tue 2 April']
price_types = ['Open', 'Close', 'High', 'Low']

np.random.seed(1)
stock_prices = np.round(np.random.random((len(companies), len(days), len(price_types))),3)
print("stock_prices.shape:", stock_prices.shape)
stock_prices

stock_prices.shape: (3, 2, 4)


array([[[0.417, 0.72 , 0.   , 0.302],
        [0.147, 0.092, 0.186, 0.346]],

       [[0.397, 0.539, 0.419, 0.685],
        [0.204, 0.878, 0.027, 0.67 ]],

       [[0.417, 0.559, 0.14 , 0.198],
        [0.801, 0.968, 0.313, 0.692]]])

In [178]:
for i, company in enumerate(companies):
    print(f"Stock prices for the {company}")
    for j, day in enumerate(days):
        print(f"Day: {day}")
        for k, price_type in enumerate(price_types):
            print(f"{price_type} Price: {stock_prices[i, j, k]}")
        print("")
    print(10*"---")
    

Stock prices for the Google
Day: Mon 1 April
Open Price: 0.417
Close Price: 0.72
High Price: 0.0
Low Price: 0.302

Day: Tue 2 April
Open Price: 0.147
Close Price: 0.092
High Price: 0.186
Low Price: 0.346

------------------------------
Stock prices for the Microsoft
Day: Mon 1 April
Open Price: 0.397
Close Price: 0.539
High Price: 0.419
Low Price: 0.685

Day: Tue 2 April
Open Price: 0.204
Close Price: 0.878
High Price: 0.027
Low Price: 0.67

------------------------------
Stock prices for the Apple
Day: Mon 1 April
Open Price: 0.417
Close Price: 0.559
High Price: 0.14
Low Price: 0.198

Day: Tue 2 April
Open Price: 0.801
Close Price: 0.968
High Price: 0.313
Low Price: 0.692

------------------------------


In [180]:
# поменяем названия осей - для наглядности
for index_axis_0, company in enumerate(companies):
    print(f"Stock prices for the {company}")
    for index_axis_1, day in enumerate(days):
        print(f"Day: {day}")
        for index_axis_2, price_type in enumerate(price_types):
            print(f"{price_type} Price: {stock_prices[index_axis_0, index_axis_1, index_axis_2]}")
        print("")
    print(10*"---")

Stock prices for the Google
Day: Mon 1 April
Open Price: 0.417
Close Price: 0.72
High Price: 0.0
Low Price: 0.302

Day: Tue 2 April
Open Price: 0.147
Close Price: 0.092
High Price: 0.186
Low Price: 0.346

------------------------------
Stock prices for the Microsoft
Day: Mon 1 April
Open Price: 0.397
Close Price: 0.539
High Price: 0.419
Low Price: 0.685

Day: Tue 2 April
Open Price: 0.204
Close Price: 0.878
High Price: 0.027
Low Price: 0.67

------------------------------
Stock prices for the Apple
Day: Mon 1 April
Open Price: 0.417
Close Price: 0.559
High Price: 0.14
Low Price: 0.198

Day: Tue 2 April
Open Price: 0.801
Close Price: 0.968
High Price: 0.313
Low Price: 0.692

------------------------------
